name: Update Instagram Posts

on:
  workflow_dispatch: # Manual trigger only

jobs:
  scrape-instagram:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        playwright install chromium
        
    - name: Run Instagram scraper
      run: |
        python scrape_instagram.py
        
    - name: Check for changes and commit
      run: |
        # Only commit if instagram_posts.json has changed
        if [ -f "instagram_posts.json" ]; then
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add instagram_posts.json
          git add images/instagram/
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🤖 Update Instagram posts and images - $(date '+%Y-%m-%d %H:%M UTC')"
            git push
            echo "Successfully updated Instagram posts and images"
          fi
        else
          echo "instagram_posts.json not found - scraper may have failed"
          exit 1
        fi